version: '3.1'

volumes:
  postgres_data:

networks:
  imageGuesser_postgres:

services:
   image_guesser_postgres:
    container_name: imageGuesser_postgres
    build:
      context: database/
    environment:
      POSTGRES_DB: imageGuesser
      POSTGRES_USER: imageGuesser
      POSTGRES_PASSWORD: imageGuesser
    ports:
      - "9091:5432"
    networks:
      - imageGuesser_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
