server:
  port: 8090
spring:
  datasource:
    sql.init.mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:9091/imageGuesser
    username: imageGuesser
    password: imageGuesser
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: create-drop
hibernate:
  hbm2ddl:
    auto: create