server:
  port: 8080
spring:
  datasource:
    sql.init.mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:9091/imageGuesser
    username: imageGuesser
    password: imageGuesser
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  hbm2ddl:
    auto: create